DROP TABLE IF EXISTS VARIABLES;
DROP TABLE IF EXISTS BONE_DENSITY;

CREATE MEMORY TABLE VARIABLES(VALUE_TABLE VARCHAR(255), NAME VARCHAR(255) NOT NULL, VALUE_TYPE VARCHAR(255), PRIMARY KEY(VALUE_TABLE, NAME))
CREATE MEMORY TABLE BONE_DENSITY(PART_ID VARCHAR(25) NOT NULL, VISIT_ID VARCHAR(25) NOT NULL, BD INTEGER, BD_2 INTEGER,PRIMARY KEY(PART_ID, VISIT_ID))