DROP TABLE IF EXISTS VARIABLES;
DROP TABLE IF EXISTS VARIABLE_ATTRIBUTES;
DROP TABLE IF EXISTS CATEGORIES;
DROP TABLE IF EXISTS BONE_DENSITY;
DROP TABLE IF EXISTS MY_TABLE;

CREATE MEMORY TABLE BONE_DENSITY(PART_ID VARCHAR(25) NOT NULL, VISIT_ID VARCHAR(25) NOT NULL, BD INTEGER, BD_2 INTEGER, PRIMARY KEY(PART_ID, VISIT_ID));