--mysql table names are case sensitive on Linux
DROP TABLE IF EXISTS variables;
DROP TABLE IF EXISTS variable_attributes;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS variables_mapping;
DROP TABLE IF EXISTS valuetables_mapping;
DROP TABLE IF EXISTS BONE_DENSITY;
DROP TABLE IF EXISTS MY_TABLE;

CREATE TABLE variables(VALUE_TABLE VARCHAR(255) NOT NULL, NAME VARCHAR(255) NOT NULL, VALUE_TYPE VARCHAR(255), MIME_TYPE VARCHAR(255), UNITS VARCHAR(255), IS_REPEATABLE BOOLEAN NOT NULL, OCCURRENCE_GROUP VARCHAR(255), PRIMARY KEY(VALUE_TABLE, NAME));
CREATE TABLE variable_attributes(VALUE_TABLE VARCHAR(255) NOT NULL, VARIABLE_NAME VARCHAR(255) NOT NULL, ATTRIBUTE_NAME VARCHAR(255) NOT NULL, ATTRIBUTE_LOCALE VARCHAR(20) NOT NULL, ATTRIBUTE_VALUE VARCHAR(255), PRIMARY KEY(VALUE_TABLE, VARIABLE_NAME, ATTRIBUTE_NAME, ATTRIBUTE_LOCALE));
CREATE TABLE categories(VALUE_TABLE VARCHAR(255) NOT NULL, VARIABLE_NAME VARCHAR(255), NAME VARCHAR(255) NOT NULL, CODE VARCHAR(255), MISSING BOOLEAN NOT NULL, PRIMARY KEY(VALUE_TABLE, VARIABLE_NAME, NAME));
CREATE TABLE variables_mapping(VALUE_TABLE VARCHAR(255) NOT NULL, NAME VARCHAR(255) NOT NULL, SQL_NAME VARCHAR(255) NOT NULL, PRIMARY KEY(NAME, VALUE_TABLE));
CREATE TABLE valuetables_mapping(NAME VARCHAR(255) NOT NULL, SQL_NAME VARCHAR(255) NOT NULL, PRIMARY KEY(NAME));

CREATE TABLE BONE_DENSITY(PART_ID VARCHAR(25) NOT NULL, VISIT_ID VARCHAR(25) NOT NULL, BD INTEGER, BD_2 INTEGER, PRIMARY KEY(PART_ID, VISIT_ID));
