DROP TABLE IF EXISTS VARIABLES;
DROP TABLE IF EXISTS VARIABLE_ATTRIBUTES;
DROP TABLE IF EXISTS CATEGORIES;
DROP TABLE IF EXISTS BONE_DENSITY;
DROP TABLE IF EXISTS MY_TABLE;

CREATE MEMORY TABLE VARIABLES(VALUE_TABLE VARCHAR(255) NOT NULL, NAME VARCHAR(255) NOT NULL, VALUE_TYPE VARCHAR(255), MIME_TYPE VARCHAR(255), UNITS VARCHAR(255), IS_REPEATABLE BOOLEAN NOT NULL, OCCURRENCE_GROUP VARCHAR(255), PRIMARY KEY(VALUE_TABLE, NAME));
CREATE MEMORY TABLE VARIABLE_ATTRIBUTES(VALUE_TABLE VARCHAR(255) NOT NULL, VARIABLE_NAME VARCHAR(255) NOT NULL, ATTRIBUTE_NAME VARCHAR(255) NOT NULL, ATTRIBUTE_LOCALE VARCHAR(20) NOT NULL, ATTRIBUTE_VALUE VARCHAR(255), PRIMARY KEY(VALUE_TABLE, VARIABLE_NAME, ATTRIBUTE_NAME, ATTRIBUTE_LOCALE)); 
CREATE MEMORY TABLE CATEGORIES(VALUE_TABLE VARCHAR(255) NOT NULL, VARIABLE_NAME VARCHAR(255), NAME VARCHAR(255) NOT NULL, CODE VARCHAR(255), MISSING BOOLEAN NOT NULL, PRIMARY KEY(VALUE_TABLE, VARIABLE_NAME, NAME)); 

CREATE MEMORY TABLE BONE_DENSITY(PART_ID VARCHAR(25) NOT NULL, VISIT_ID VARCHAR(25) NOT NULL, BD INTEGER, BD_2 INTEGER, PRIMARY KEY(PART_ID, VISIT_ID));
