--mysql table names are case sensitive on Linux
DROP TABLE IF EXISTS "value_tables";
DROP TABLE IF EXISTS "variables";
DROP TABLE IF EXISTS "variable_attributes";
DROP TABLE IF EXISTS "categories";
DROP TABLE IF EXISTS "category_attributes";
DROP TABLE IF EXISTS BONE_DENSITY;
DROP TABLE IF EXISTS MY_TABLE;
DROP TABLE IF EXISTS "mydatasourcenodb_MY_TABLE";

CREATE TABLE BONE_DENSITY(PART_ID INTEGER NOT NULL, VISIT_ID VARCHAR(25) NOT NULL, BD INTEGER, BD_2 INTEGER, PRIMARY KEY(PART_ID));