DROP TABLE IF EXISTS LOBS;

CREATE TABLE LOBS(PART_ID VARCHAR(25) NOT NULL, MY_BLOB BLOB, MY_CLOB CLOB, PRIMARY KEY(PART_ID));
INSERT INTO LOBS(PART_ID, MY_BLOB, MY_CLOB) VALUES('1', X'89504E470D0A1A0A', 'a long text');
