--mysql table names are case sensitive on Linux
DROP TABLE IF EXISTS value_tables;
DROP TABLE IF EXISTS variables;
DROP TABLE IF EXISTS variable_attributes;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS category_attributes;
DROP TABLE IF EXISTS BONE_DENSITY;
DROP TABLE IF EXISTS MY_TABLE;

CREATE TABLE value_tables(DATASOURCE VARCHAR(255) NOT NULL, NAME VARCHAR(255) NOT NULL, ENTITY_TYPE VARCHAR(255) NOT NULL, CREATED DATETIME, UPDATED DATETIME, SQL_NAME VARCHAR(255) NOT NULL, PRIMARY KEY(DATASOURCE, NAME));
CREATE TABLE variables(DATASOURCE VARCHAR(255) NOT NULL, VALUE_TABLE VARCHAR(255) NOT NULL, NAME VARCHAR(255) NOT NULL, VALUE_TYPE VARCHAR(255), MIME_TYPE VARCHAR(255), UNITS VARCHAR(255), IS_REPEATABLE BOOLEAN NOT NULL, OCCURRENCE_GROUP VARCHAR(255), INDEX INT, SQL_NAME VARCHAR(255) NOT NULL, PRIMARY KEY(DATASOURCE, VALUE_TABLE, NAME));
CREATE TABLE variable_attributes(DATASOURCE VARCHAR(255) NOT NULL, VALUE_TABLE VARCHAR(255) NOT NULL, VARIABLE VARCHAR(255) NOT NULL, NAME VARCHAR(255) NOT NULL, LOCALE VARCHAR(20) NOT NULL, VALUE VARCHAR(255), PRIMARY KEY(DATASOURCE, VALUE_TABLE, VARIABLE, NAME, LOCALE));
CREATE TABLE categories(DATASOURCE VARCHAR(255) NOT NULL, VALUE_TABLE VARCHAR(255) NOT NULL, VARIABLE VARCHAR(255), NAME VARCHAR(255) NOT NULL, MISSING BOOLEAN NOT NULL, PRIMARY KEY(VALUE_TABLE, VARIABLE, NAME));
CREATE TABLE category_attributes(DATASOURCE VARCHAR(255) NOT NULL, VALUE_TABLE VARCHAR(255) NOT NULL, VARIABLE VARCHAR(255) NOT NULL, CATEGORY VARCHAR(255) NOT NULL, NAME VARCHAR(255) NOT NULL, LOCALE VARCHAR(20) NOT NULL, VALUE VARCHAR(255), PRIMARY KEY(DATASOURCE, VALUE_TABLE, VARIABLE, CATEGORY, NAME, LOCALE));

CREATE TABLE BONE_DENSITY(PART_ID VARCHAR(25) NOT NULL, VISIT_ID VARCHAR(25) NOT NULL, BD INTEGER, BD_2 INTEGER, PRIMARY KEY(PART_ID, VISIT_ID));
